[build]
  publish = "."

[[redirects]]
  from = "/Snake/*"
  to = "/Snake/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[build.environment]
  NODE_VERSION = "18"
